fastlane_version "1.89.0"

default_platform :ios

platform :ios do
  lane :test do
    scan(
    project: "SwiftyNotificationCenter.xcodeproj",
    scheme: "SwiftyNotificationCenter",
    clean: true,
    configuration: "Debug",
    device: "iPhone 6s (9.3)",
    skip_build: true
    )
  end
end
