fastlane_version "1.81.0"

lane :test do
  scan(
  project: "SwiftyNotificationCenter.xcodeproj",
  scheme: "SwiftyNotificationCenter",
  clean: true,
  configuration: "Debug",
  destination: "platform=iOS Simulator,name=iPhone 6s,OS=9.3",
  skip_build: true
  )
end
