fastlane_version "1.81.0"

lane :test do
  scan(
  project: "SwiftyNotificationCenter.xcodeproj",
  scheme: "SwiftyNotificationCenter",
  clean: true,
  configuration: "Debug",
  device: "iPhone 6s (9.3)"
  )
end